### ISSUE TITLE
Cloudstack Stuck in Pending - Scalarizr Fails to Start

### ISSUE THREAD

**Issue by stajkowski** [Scalr/scalarizr#14]
Getting this message: 2015-12-22 23:17:27,788-05:00 - ERROR - scalarizr.app - No user-data provider that fits this cloud environment is available

/var/log/scalarizr_debug.log
--------
2015-12-22 23:17:17,748-05:00 - DEBUG - common.utils.subprocess2 - Executing subprocess: (['/bin/mount', '/dev/disk/by-label/config-2', '/mnt/config'],)
2015-12-22 23:17:17,750-05:00 - DEBUG - agent.cloudinit.metadata.personality - Fitting...
2015-12-22 23:17:17,750-05:00 - DEBUG - agent.cloudinit.metadata.personality - Does not fit: User-data files ['/etc/scalr/private.d/.user-data', '/etc/.scalr-user-data'] do not exist or not accessible.
2015-12-22 23:17:17,751-05:00 - DEBUG - agent.cloudinit.metadata.cloudstack - Fitting...
2015-12-22 23:17:17,752-05:00 - DEBUG - agent.cloudinit.metadata.cloudstack - Does not fit: DHCP server not found in leases file /var/lib/dhcp/dhclient.leases
2015-12-22 23:17:17,752-05:00 - DEBUG - agent.cloudinit.metadata.openstack - Fitting...
2015-12-22 23:17:17,756-05:00 - DEBUG - agent.cloudinit.metadata.gce - Fitting...
2015-12-22 23:17:17,756-05:00 - DEBUG - agent.cloudinit.metadata.azure - Fitting...
2015-12-22 23:17:17,758-05:00 - DEBUG - agent.cloudinit.metadata.ec2 - Fitting...
2015-12-22 23:17:17,765-05:00 - DEBUG - common.utils.subprocess2 - Subprocess stderr: /bin/sh: 1: vmtoolsd: not found

2015-12-22 23:17:17,766-05:00 - DEBUG - common.utils.subprocess2 - Subprocess returncode: 127
2015-12-22 23:17:17,766-05:00 - DEBUG - agent.cloudinit.metadata.verizon - Does not fit: Command 'vmtoolsd --cmd "info-get guestinfo.personality.count"' returned non-zero exit status 127
stdout:
stderr: /bin/sh: 1: vmtoolsd: not found

2015-12-22 23:17:17,775-05:00 - DEBUG - common.utils.subprocess2 - Subprocess stderr: mount: special device /dev/disk/by-label/config-2 does not exist

2015-12-22 23:17:17,775-05:00 - DEBUG - common.utils.subprocess2 - Subprocess returncode: 32
2015-12-22 23:17:17,775-05:00 - DEBUG - agent.cloudinit.metadata.configdrive - Does not fit: Command ['/bin/mount', '/dev/disk/by-label/config-2', '/mnt/config'] returned non-zero exit status 32
stdout:
stderr: mount: special device /dev/disk/by-label/config-2 does not exist

2015-12-22 23:17:17,883-05:00 - DEBUG - agent.cloudinit.metadata.gce - Does not fit: HTTPConnectionPool(host='metadata', port=80): Max retries exceeded with url: /computeMetadata/v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fdba0b82490>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2015-12-22 23:17:18,778-05:00 - DEBUG - agent.cloudinit.metadata.ec2 - Does not fit: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/instance-id (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fdba0b82fd0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
2015-12-22 23:17:18,779-05:00 - DEBUG - agent.cloudinit.metadata.openstack - Does not fit: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /openstack/latest/meta_data.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fdba006e210>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
2015-12-22 23:17:27,787-05:00 - DEBUG - agent.cloudinit.metadata.azure - Does not fit
2015-12-22 23:17:27,788-05:00 - ERROR - scalarizr.app - No user-data provider that fits this cloud environment is available
Traceback (most recent call last):
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-4.1.16-py2.7.egg/scalarizr/app.py", line 562, in main
    svs.start()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-4.1.16-py2.7.egg/scalarizr/app.py", line 684, in start
    and server_id != metadata.get_metadata().user_data['serverid']:
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/fatmouse_agent-0.1.65a065d-py2.7.egg/common/utils/mixutil.py", line 312, in wrapper
    func._memorized = func(*args, **kwds)
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-4.1.16-py2.7.egg/scalarizr/util/metadata.py", line 40, in user_data
    if self.provider.name in ['openstack', 'configdrive']:
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-4.1.16-py2.7.egg/scalarizr/util/metadata.py", line 35, in provider
    return metadata.current_provider()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/fatmouse_agent-0.1.65a065d-py2.7.egg/agent/cloudinit/metadata.py", line 375, in current_provider
    globals()['provider'] = _get_provider()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/fatmouse_agent-0.1.65a065d-py2.7.egg/agent/cloudinit/metadata.py", line 415, in _get_provider
    'No user-data provider that fits this cloud environment is available')
NoProviderError: No user-data provider that fits this cloud environment is available

**Comment by DicsyDel** [comment]
What version of Cloudstack you're using? Also can you please provide contents of this folder: /var/lib/dhcp

Thanks,
Igor

**Comment by DicsyDel** [comment]
Also, the best way to get a support for opensource scalr is our google group: https://groups.google.com/forum/#!forum/scalr-discuss

Regards,
Igor

**Comment by DicsyDel** [comment]
Closing because of inactivity.
