### ISSUE TITLE
Scalarizr fails to start on Windows 2012 images in Openstack

### ISSUE THREAD

**Issue by jagojkov** [Scalr/scalarizr#16]
We have an Openstack env without the metadata service so we rely on config-drive.
Version 4.8.3(stable) and 4.11.3(latest)

With the Windows client of scalarizr, when an instance first comes up it logs the below error and stops.

2016-09-26 22:37:39,230 - DEBUG - agent.scalrinit.metadata - User-data providers that fit: [<ConfigDriveProvider>, <DefaultProvider>]
2016-09-26 22:37:39,230 - DEBUG - agent.scalrinit.metadata.configdrive - Found meta_data.json
2016-09-26 22:37:39,230 - DEBUG - agent.scalrinit.metadata.configdrive - Found meta_data.json
2016-09-26 22:37:39,230 - ERROR - agent.scalrinit.app - Scalr-Init can't obtain metadata: User-data file /mnt/config\openstack\latest\meta_data.json do not exist or not accessible.
2016-09-26 22:37:39,230 - INFO - upd.client - Stopping UpdateClient
2016-09-26 22:37:39,230 - INFO - upd.client - Stopped
2016-09-26 22:37:39,230 - ERROR - upd.client - Detailed exception information below:
Traceback (most recent call last):
  File "C:\opt\scalarizr\4.8.3\embedded\lib\site-packages\scalarizr-4.8.3-py2.7.egg\scalarizr\updclient\app.py", line 183, in do_start
    agent.scalrinit.app.main_start()
  File "C:\opt\scalarizr\4.8.3\embedded\lib\site-packages\fatmouse_agent-0.1.7df08e00c-py2.7.egg\agent\scalrinit\app.py", line 25, in main_start
    instance_id = metadata.instance_id()
  File "C:\opt\scalarizr\4.8.3\embedded\lib\site-packages\fatmouse_agent-0.1.7df08e00c-py2.7.egg\common\utils\mixutil.py", line 294, in wrapper
    func._memorized = func(*args, **kwds)
  File "C:\opt\scalarizr\4.8.3\embedded\lib\site-packages\fatmouse_agent-0.1.7df08e00c-py2.7.egg\agent\scalrinit\metadata.py", line 558, in instance_id
    return create_provider(get_datasource()['instance_id']).instance_id
  File "C:\opt\scalarizr\4.8.3\embedded\lib\site-packages\fatmouse_agent-0.1.7df08e00c-py2.7.egg\agent\scalrinit\metadata.py", line 333, in instance_id
    return json.loads(self.user_data)['uuid']
  File "C:\opt\scalarizr\4.8.3\embedded\lib\site-packages\fatmouse_agent-0.1.7df08e00c-py2.7.egg\agent\scalrinit\metadata.py", line 326, in user_data
    .format(self._metadata_path))
NoUserdataError: User-data file /mnt/config\openstack\latest\meta_data.json do not exist or not accessible.

Keep in mind that this is a Windows server so /mnt/config does not exist.  The actual config drive is d:\

**Comment by maratkomarov** [comment]
@jagojkov issue fixed in agent v4.11.6 If you use Hosted Scalr repos, fix already there.
