### ISSUE TITLE
Using Chef Role with override attributes results in error

### ISSUE THREAD

**Issue by dgorst** [Scalr/scalarizr#3]
When using a Chef role with override attributes in a Farm role configuration, I always get the following error regardless of the contents of the attribute JSON:

```
2014-10-10 07:31:58,318 - ERROR - scalarizr.ops.system.init - Operation "system.init" (id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeee) failed. Reason: 'int' object does not support item assignment
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/scalarizr/api/operation.py", line 155, in _in_progress
    self._completed(self.func(self, *self.func_args, **self.func_kwds))
  File "/usr/lib/python2.6/site-packages/scalarizr/handlers/lifecycle.py", line 413, in handler
    bus.fire("host_init_response", message)
  File "/usr/lib/python2.6/site-packages/scalarizr/libs/bases.py", line 33, in fire
    ln(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/scalarizr/handlers/chef.py", line 178, in on_host_init_response
    self._with_json_attributes['run_list'] = ["role[%s]" % self._chef_data['role']]
```

Any ideas?

**Comment by DicsyDel** [comment]
Closing because of inactivity.
