### ISSUE TITLE
Scalarizr support CentOS7

### ISSUE THREAD

**Issue by wingZero21** [Scalr/scalarizr#5]
Hi,

Can you confirm if scalarizr works with CentOS7 currently.

I have installed the below RPM's from the repo but when attempting to start the agent I am getting the below currently.

Details:
```
rpm -qa | grep scalar
scalarizr-3.1.11-1.x86_64
scalarizr-cloudstack-3.1.11-1.x86_64

-- Logs begin at Thu 2014-11-27 08:44:39 GMT, end at Thu 2014-11-27 09:30:59 GMT. --
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: systemd services. SysV configuration data might be overridden by native
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: systemd configuration.
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: If you want to list systemd services use 'systemctl list-unit-files'.
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: To see services enabled on particular target use
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: 'systemctl list-dependencies [target]'.
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: error reading information on service iptables: No such file or directory <args>: ('/sbin/chkconfig', '--list', 'iptables')
Nov 27 09:30:59 centos7-prod-dc1 scalarizr[11208]: [FAILED]
Nov 27 09:30:59 centos7-prod-dc1 systemd[1]: scalarizr.service: control process exited, code=exited status=1
Nov 27 09:30:59 centos7-prod-dc1 systemd[1]: Failed to start SYSV: Scalarizr is a part of Scalr project.
```

When trying to run the scalarizr command I am seeing the below output.

```
Traceback (most recent call last):
  File "/usr/bin/scalarizr", line 9, in <module>
    load_entry_point('scalarizr==3.1.11', 'console_scripts', 'scalarizr')()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 356, in load_entry_point
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 2431, in load_entry_point
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 2147, in load
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/app.py", line 19, in <module>
    from scalarizr.handlers import MessageListener
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/handlers/__init__.py", line 9, in <module>
    from scalarizr.linux import iptables, pkgmgr
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/linux/iptables.py", line 489, in <module>
    if enabled():
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/linux/iptables.py", line 465, in enabled
    out = redhat.chkconfig(list="iptables")[0]
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/linux/redhat.py", line 7, in chkconfig
    long=long_kwds))
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/linux/__init__.py", line 49, in system
    return util.system2(*args, **kwds)
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.1.11-py2.7.egg/scalarizr/util/__init__.py", line 305, in system2
    raise ExcClass(error_text, out and out.strip() or '', err and err.strip() or '', p.returncode, popenargs[0])
scalarizr.linux.LinuxError: /sbin/chkconfig (code: 1) <out>:  <err>: Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

error reading information on service iptables: No such file or directory <args>: ('/sbin/chkconfig', '--list', 'iptables')
```

**Comment by maratkomarov** [comment]
CentOS 7 support was added in 3.1.22 http://update.scalr.net/

**Comment by wingZero21** [comment]
Hi,

When trying this currently I am getting the below error.

Details:
```
2015-01-27 08:13:47,071+00:00 - ERROR - scalarizr.app - ("Can't find virtual router. No file matching pattern: %s", '/var/lib/dhc*/dhclient*.leases')
Traceback (most recent call last):
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/app.py", line 556, in main
    svs.start()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/app.py", line 651, in start
    _init_platform()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/app.py", line 326, in _init_platform
    bus.platform = PlatformFactory().new_platform(platform_name)
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/platform/__init__.py", line 108, in new_platform
    self._platforms[name] = pl.get_platform()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/platform/cloudstack/__init__.py", line 22, in get_platform
    return CloudStackPlatform()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/platform/cloudstack/__init__.py", line 55, in __init__
    self.refresh_virtual_router_addr()
  File "/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/platform/cloudstack/__init__.py", line 64, in refresh_virtual_router_addr
    raise PlatformError("Can't find virtual router. No file matching pattern: %s", leases_pattern)
PlatformError: ("Can't find virtual router. No file matching pattern: %s", '/var/lib/dhc*/dhclient*.leases')
```

**Comment by wingZero21** [comment]
Hi,

I think I have fixed this by amending the below line in the code.

Can you advise if this needs to be amended?

Details:
File 
/opt/scalarizr/embedded/lib/python2.7/site-packages/scalarizr-3.3.2-py2.7.egg/scalarizr/platform/cloudstack/__init__.py

Amendment
```
leases_pattern = '/var/lib/dhclient/dhclient*.lease'
```

**Comment by maratkomarov** [comment]
I can't find your pull request for such issue. 
Thanks for the report, we'll correct leases pattern in next minor release.

**Comment by wingZero21** [comment]
Hi,

Also after making this amendment, I am able to create the role. However when attempting to launch it seems to get stuck on pending currently.

Any idea on what might be causing this to occur.

![pending](https://cloud.githubusercontent.com/assets/5137059/5916563/899581f0-a60a-11e4-98a8-989f18477991.png)

**Comment by maratkomarov** [comment]
Make sure role is using `latest` Scalarizr repository: Advanced tab (for the farm role) or Farm extend info (for the whole farm)

**Comment by wingZero21** [comment]
Hey,

We are retrying this. We think this is due to the image not automatically starting the scalr agent upon reboot.

Will let you know if this makes any difference.

**Comment by wingZero21** [comment]
Hi,

Looks like its still failing and sitting in pending currently.

Is this because the scalarizr agent is not been updated on scalr itself?
